package com.company.Module2.Lab3;

public enum QueryType {
    ADD_GENRE, DELETE_GENRE, ADD_FILM, DELETE_FILM, UPDATE_FILM, COUNT_FILMS_BY_GENRE, GET_FILM_BY_NAME,
    GET_FILMS_BY_GENRE, GET_GENRES;
}
